FROM python:3.8

RUN pip install autopep8 flake8 rope

RUN pip install numpy pandas tensorflow matplotlib
    
RUN pip3 install torch torchvision torchaudio \
    --extra-index-url https://download.pytorch.org/whl/cpu
